### ISSUE TITLE
Hi, which software did u used rendering the bvh animation in paper?

### ISSUE THREAD

**Issue by jinfagang** [PeizhuoLi/ganimator#1]
Just wanna ask. It definitely not blender or maya .

**Comment by PeizhuoLi** [comment]
We use Blender for all the rendering. The related code for rendering skeletal animation is made public [here](https://github.com/DeepMotionEditing/deep-motion-editing#rendering).

**Comment by jinfagang** [comment]
thanks, how did u render the Maximo character Joe without texture but pure blue color?

**Comment by PeizhuoLi** [comment]
It's done by changing the material of the character to a pure color material.
