### ISSUE TITLE
some question about Training a Conditional Generator

### ISSUE THREAD

**Issue by visonpon** [PeizhuoLi/ganimator#11]
Hi, Peizhou, in the **Training a Conditional Generator** part , you mentioned that  we can change the conditional joints. 
 I wonder if I change the root joints as uppper body joints, could this model be used for generate the full body motion? Hope you can share more details on how to change the  get_layered_mask() function to use other body joints as condition., thanks~

**Comment by PeizhuoLi** [comment]
Of course! get_layered_mask() returns the indices to the channels in the animation representation that you wish to use as the condition. You may simply return the desired channel indices without any other modification.

**Comment by visonpon** [comment]
got it ,thanks~
