### ISSUE TITLE
problems in bvh channels

### ISSUE THREAD

**Issue by JiuZhouu** [PeizhuoLi/ganimator#12]
Hi, thanks for the great paper and library!

I'm also attempting to train the model on a custom .bvh animation, which is downloaded from Mixamo as .fbx files.

When I tried to change .fbx into .bvh file, I put .fbx into Blender and exported as .bvh. However, the number of channels of child joints is not fixed, seems to be some 3 and some 6.
[dance.txt](https://github.com/PeizhuoLi/ganimator/files/9845899/dance.txt)

Is there any way to export .bvh files and limit the channels?

**Comment by JiuZhouu** [comment]
1. Hi there，I used the[ fbx2bvh.py](https://github.com/DeepMotionEditing/deep-motion-editing/blob/master/blender_rendering/utils/fbx2bvh.py) from deep-motion-editing.

it seemingly worked. Thank you for great code!

2. BTW, is there any way to modify the key frame easily? (for the demo key-frame-editing)

**Comment by PeizhuoLi** [comment]
You may try to use MotionBuilder or Blender to edit

**Comment by JiuZhouu** [comment]
Thanks, I would try it.
