### ISSUE TITLE
Could you provide style-transfer and key-frame editing?

### ISSUE THREAD

**Issue by donghaoye** [PeizhuoLi/ganimator#3]
This is excellent work.  Could you provide demos for style transfer and key-frame editing?

**Comment by PeizhuoLi** [comment]
Thanks for asking. We are finalizing the code and will release the rest part of the work in the coming weeks.

**Comment by donghaoye** [comment]
Looking forward to the rest part.

**Comment by hemath1001** [comment]
Looking forward to it!

**Comment by hemath1001** [comment]
> Thanks for asking. We are finalizing the code and will release the rest part of the work in the coming weeks.

Looking forward to

**Comment by hemath1001** [comment]
> Thanks for asking. We are finalizing the code and will release the rest part of the work in the coming weeks.

Thanks for your great work! Is there any new information about the rest part of the code?~~

**Comment by wyysf-98** [comment]
Hi Peizhuo! Thanks you for your great work! ! !  Could you provide the timeline of the evaluation code release? 
Thanks a lot :) @PeizhuoLi

**Comment by PeizhuoLi** [comment]
Sorry for the delay. I'm aiming at releasing everything next week. It took longer than I expected since the evaluation part contains a submodule implemented with C++ (for efficiency consideration).

**Comment by hemath1001** [comment]
> Sorry for the delay. I'm aiming at releasing everything next week. It took longer than I expected since the evaluation part contains a submodule implemented with C++ (for efficiency consideration).

Wow that's awesome! Looking forward to it :-D  @PeizhuoLi

**Comment by wyysf-98** [comment]
> Sorry for the delay. I'm aiming at releasing everything next week. It took longer than I expected since the evaluation part contains a submodule implemented with C++ (for efficiency consideration).

Looking forward to it, too !!! Thanks again for your prompt reply :>

**Comment by PeizhuoLi** [comment]
All the functions mentioned have been released.
