### ISSUE TITLE
Re BVH source 

### ISSUE THREAD

**Issue by GuyTevet** [PeizhuoLi/ganimator#4]
Hi Peizhuo! Thank you for your great work!
I want to try and run your code on different skeleton structures. What is the source of the crab bvh? Do they have there some other animated animals to try on?

Thanks:)

**Comment by PeizhuoLi** [comment]
Hi Guy! Our animal animation are mainly collected from Truebones Motion Animation studios [here](https://truebones.gumroad.com). There are quite some animation of animals like [this](https://truebones.gumroad.com/l/XAREU) one. I can't find exactly from which one obtain the crab but it should be there somewhere. Hope this can be helpful.

**Comment by GuyTevet** [comment]
Very cool! Thanks 🙏🏼😊
