### ISSUE TITLE
Motion Mixing

### ISSUE THREAD

**Issue by Neptune-Trojans** [PeizhuoLi/ganimator#8]
Hi,

I want to train with several bvh files and to use motion mixing feature.
From what I see bvh_name gets single string, and multiple_sequences is deprecated.

How you actually do it ?

Thanks for assistance.

**Comment by Neptune-Trojans** [comment]
Hi, the same question about conditional generation, generation by given path .
Is is included in current code ?If so how I can use it ?

**Comment by PeizhuoLi** [comment]
Yes. It is the same case. The application part hasn't been released.

**Comment by Neptune-Trojans** [comment]
Thanks for your answers, I will wait for the new release.
